cleanerBotA:
  L2_zoneA:
    level_name: TRL_L2
    path: [[39.482, -29.097, 0.0], [39.768, -32.208, 0.0], [36.226, -33.91, 0.0], [36.281, -30.57, 0.0], [38.333, -30.266, 0.0]]
  L2_zoneB:
    level_name: TRL_L2
    path: [[84.056, -25.616, 0.0], [84.1, -20.412, 0.0], [91.945, -21.24, 0.0], [85.454, -24.604, 0.0]]
  L2_zoneC:
    level_name: TRL_L2
    path: [[120.032, -28.951, 0.0], [119.966, -29.96, 0.0]]
  L3_zoneA:
    level_name: TRL_L3
    path: [[34.555, -28.176, 0.0], [33.693, -29.106, 0.0]]
  L3_zoneB:
    level_name: TRL_L3
    path: []
  L3_zoneC:
    level_name: TRL_L3
    path: []
  L4_zoneA:
    level_name: TRL_L4
    path: [[11.795, 73.257, 0.0], [10.57, 73.872, 0.0]]
  L4_zoneB:
    level_name: TRL_L4
    path: [[2.033, 57.275, 0.0], [3.433, 53.301, 0.0]]
  L4_zoneC:
    level_name: TRL_L4
    path: [[26.187, -27.36, 0.0], [29.248, -27.333, 0.0], [26.187, -29.33, 0.0]]
  L5_zoneA:
    level_name: TRL_L5
    path: []
  L5_zoneB:
    level_name: TRL_L5
    path: []
  L5_zoneC:
    level_name: TRL_L5
    path: []
  L6_zoneA:
    level_name: TRL_L6
    path: []
  L6_zoneB:
    level_name: TRL_L6
    path: []
  L6_zoneC:
    level_name: TRL_L6
    path: []
